MOCK_DATA = [
    {
        "symbol": "sy1",
        "companyName": "cn1",
        "exchange": "ex1",
        "industry": "in1",
        "website": "ws1",
        "description": "dc1",
        "CEO": "ceo1",
        "issueType": "is1",
        "sector": "sc1",
    },
    {
        "symbol": "sy2",
        "companyName": "cn2",
        "exchange": "ex2",
        "industry": "in2",
        "website": "ws2",
        "description": "dc2",
        "CEO": "ceo2",
        "issueType": "is2",
        "sector": "sc2",
    },
    {
        "symbol": "sy3",
        "companyName": "cn3",
        "exchange": "ex3",
        "industry": "in3",
        "website": "ws3",
        "description": "dc3",
        "CEO": "ceo3",
        "issueType": "is3",
        "sector": "sc3",
    },
    {
        "symbol": "sy4",
        "companyName": "cn4",
        "exchange": "ex4",
        "industry": "in4",
        "website": "ws4",
        "description": "dc4",
        "CEO": "ceo4",
        "issueType": "is4",
        "sector": "sc4",
    },
    {
        "symbol": "sy5",
        "companyName": "cn5",
        "exchange": "ex5",
        "industry": "in5",
        "website": "ws5",
        "description": "dc5",
        "CEO": "ceo5",
        "issueType": "is5",
        "sector": "sc5",
    },
    {
        "symbol": "sy6",
        "companyName": "cn6",
        "exchange": "ex6",
        "industry": "in6",
        "website": "ws6",
        "description": "dc6",
        "CEO": "ceo6",
        "issueType": "is6",
        "sector": "sc6",
    },
    {
        "symbol": "sy7",
        "companyName": "cn7",
        "exchange": "ex7",
        "industry": "in7",
        "website": "ws7",
        "description": "dc7",
        "CEO": "ceo7",
        "issueType": "is7",
        "sector": "sc7",
    },
    {
        "symbol": "sy8",
        "companyName": "cn8",
        "exchange": "ex8",
        "industry": "in8",
        "website": "ws8",
        "description": "dc8",
        "CEO": "ceo8",
        "issueType": "is8",
        "sector": "sc8",
    },
    {
        "symbol": "sy9",
        "companyName": "cn9",
        "exchange": "ex9",
        "industry": "in9",
        "website": "ws9",
        "description": "dc9",
        "CEO": "ceo9",
        "issueType": "is9",
        "sector": "sc9",
    },
    {
        "symbol": "sy",
        "companyName": "cn",
        "exchange": "ex",
        "industry": "in",
        "website": "ws",
        "description": "dc",
        "CEO": "ceo",
        "issueType": "is",
        "sector": "sc",
    }
]
